location: .gitman
sources:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: added_dialect_file
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: subt_virtual
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: subt_virtual
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: master
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: callback_fix
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 3.0a
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: v2.0.0
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: 8deab345e2560245c021b772cf675a9be54cee04
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: 81ba1fbf9e1b72f4a65ea2b58910d173cfa38304
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: 2fcc753497f5f76b32d4b2a22bc918afbad6970c
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: 4e95e00180b6bbbd0f74f0523bde5776f70dbf4b
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: f7ba647af2117484432372f207d5dc30f9ae26c9
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: bf7ea90ce58b98526cd359d8f70659451dbbcff6
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: b6d8d012ac789a919964e97d4fc277d1a3793ac0
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: 4bc21a878ca5d2728014648fd020215edca52ebd
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: 0f786bfa2036a75a0d10e405e42c78b6e6ce452e
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: e4e2ec44f0c98d584219085d9fb3c3e8d7a98ecd
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: 57980f8f1985d3049176c0983ddb0a3aeb2a6e6e
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: dda5572924772d9311085400d7604b8bf2a02b2f
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: 4375aae11b623e26d5aa8b00b2922747e440e3d5
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: 6eeee2bd02e0e01a340e8d140f8b51f269c194bb
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: b4344e75e9afa93010ffc20c3918ecfbab1848e4
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    type: git
    sparse_paths:
      -
    link:
    links:
      -
    scripts:
      - git submodule update --init --recursive
groups:
  -
default_group: ''
