location: .gitman
sources:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: 19c4fc6006d88636a5b8b5f2e608bfcdf80e6620
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: https://github.com/ctu-mrs/mavros
  sparse_paths:
  -
  rev: added_dialect_file
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_bumper
  type: git
  repo: https://github.com/ctu-mrs/mrs_bumper.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_bumper
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: https://github.com/ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: https://github.com/ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: https://github.com/ctu-mrs/mrs_optic_flow.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_rviz_plugins
  type: git
  repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_rviz_plugins
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_controllers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_general
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_managers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_managers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_odometry
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_status
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_testing
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trackers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_trackers
  scripts:
  - git submodule update --init --recursive
- name: tmux
  type: git
  repo: https://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 3.0a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: https://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: v2.0.0
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: 19c4fc6006d88636a5b8b5f2e608bfcdf80e6620
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: https://github.com/ctu-mrs/mavros
  sparse_paths:
  -
  rev: 8deab345e2560245c021b772cf675a9be54cee04
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_bumper
  type: git
  repo: https://github.com/ctu-mrs/mrs_bumper.git
  sparse_paths:
  -
  rev: ecb3698321ba80c74888aef875f2927718fbfa18
  link: ros_packages/mrs_bumper
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: https://github.com/ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: e20bff031039afc9a82c07e4b4be0bc3865d3af5
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: c8250c11529ef13721e39dd87d15f6effd94133d
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: https://github.com/ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: d9ce466f9bb87ce63f9ab778e5c4c4001c1a1d26
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: https://github.com/ctu-mrs/mrs_optic_flow.git
  sparse_paths:
  -
  rev: 65babd83c7b21baf5114f467f19e0538d5e14577
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_rviz_plugins
  type: git
  repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
  sparse_paths:
  -
  rev: 154bd1b01caf08d62b2b45403eaf13b9a63504c6
  link: ros_packages/mrs_rviz_plugins
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_controllers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: 8c5eba48251f981c7f9d51742deeb06581cb191f
  link: ros_packages/mrs_uav_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_general
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: d68a5fbdcd95e6a15c3824a73cda03bdcbc8962e
  link: ros_packages/mrs_uav_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_managers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: 6e77211a8f65d6b4733059a3b16b3bb70da33b00
  link: ros_packages/mrs_uav_managers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_odometry
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: ac59530aebbe6e38eda390b5fb637e82f5055ef4
  link: ros_packages/mrs_uav_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_status
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: 6fb0a55c8957927857d4b6629e427dcf7602fce8
  link: ros_packages/mrs_uav_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_testing
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: 292dedba37863b87ce1dca5236f6088269dc4bb8
  link: ros_packages/mrs_uav_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trackers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: 9c14faa55d11e0c26f87bc33cc31abda9a02bbae
  link: ros_packages/mrs_uav_trackers
  scripts:
  - git submodule update --init --recursive
- name: tmux
  type: git
  repo: https://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: https://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
