location: .gitman
sources:
  - repo: https://github.com/ctu-mrs/mrs_multirotor_simulator
    name: mrs_multirotor_simulator
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_multirotor_simulator
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/tf2
    name: tf2
    rev: warning_fix
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/tf2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_state_estimators.git
    name: mrs_uav_state_estimators
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_state_estimators
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:ctu-mrs/mrs_uav_hw_api.git
    name: mrs_uav_hw_api
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_hw_api
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_general
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: hw_api
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/nlopt_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 3.0a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmux
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: v2.0.0
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmuxinator
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: c943805307bd656fe3bad45d55040b9d8dd088f3
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: 8372b589bc2ee0cfdf5c0099026729713305ab40
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: c57d501d0dcf695054e634c8c4695007f60f8ae0
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: 2865824e1fb1e314021a2294f1351bdb2e9e9eae
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: 9577862296c01cb4e49163932973045effcdba50
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: d15633168fff903f8938f5e3c878243ada254114
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_general
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: 5032cfd136796b0956abf9b0b61b8e5e782a0359
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: 03f0d5d4478415a031f9db047a6dc12653543ce9
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: 38fe4acea8bf632a71c234351045b0039b4c00a0
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: 48cecf10958668c8fc167f1d3fc7c005f9b2e903
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: ba540e9b888ef19409f8a9868e83d0fd4d6b0167
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/nlopt_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmux
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmuxinator
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/tf2
    name: tf2
    rev: 89f90c21fc13868ee02e853663a226130471ea8c
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/tf2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_multirotor_simulator
    name: mrs_multirotor_simulator
    rev: 6de0268dc241ebf72e7fb5430727ff9f2385af3f
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_multirotor_simulator
    scripts:
      - git submodule update --init --recursive
  - repo: git@github.com:ctu-mrs/mrs_uav_hw_api.git
    name: mrs_uav_hw_api
    rev: df5b03a03d2febc91dea6a1302a92bad9fe98336
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_hw_api
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_state_estimators.git
    name: mrs_uav_state_estimators
    rev: 3fcab682992bc264b18975d4e6c93aace87f42bc
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_state_estimators
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
