location: .gitman
sources:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: added_dialect_file
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: master
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: callback_fix
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 3.0a
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: v2.0.0
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: 8deab345e2560245c021b772cf675a9be54cee04
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: 81ba1fbf9e1b72f4a65ea2b58910d173cfa38304
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: 2fcc753497f5f76b32d4b2a22bc918afbad6970c
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: 4e95e00180b6bbbd0f74f0523bde5776f70dbf4b
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: 39c50bb2baa16a4f7a40f39c7445c9abc756664b
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: bf7ea90ce58b98526cd359d8f70659451dbbcff6
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: 9d2385383f632caedec6081723e2fcc4cd175974
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: 4a4c1f60fa6ba89d1114c0b3ccc40eeb1f1c8b60
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: 0f786bfa2036a75a0d10e405e42c78b6e6ce452e
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: e4e2ec44f0c98d584219085d9fb3c3e8d7a98ecd
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: af71a0c73b7f43618b81b4b31a2a08bbd81adf1d
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: dda5572924772d9311085400d7604b8bf2a02b2f
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: 95e379000a767ac5c862d78027b67c53eccb1c61
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: 6475ef6e16091a9e76babd38dec0c35e99af6e02
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: b4344e75e9afa93010ffc20c3918ecfbab1848e4
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
groups:
  -
default_group: ''
