location: .gitman
sources:
- name: tmux
  type: git
  repo: http://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 3.0a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: http://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: v2.0.0
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: a131e4bd665d2dc7f822797faf13d783fcd4bb8a
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: git@github.com:ctu-mrs/mavros.git
  sparse_paths:
  -
  rev: header_fix
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_controllers
  type: git
  repo: git@github.com:ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_general
  type: git
  repo: git@github.com:ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: git@github.com:ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: git@github.com:ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: git@github.com:ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_odometry
  type: git
  repo: git@github.com:ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: git@github.com:ctu-mrs/mrs_optic_flow.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_status
  type: git
  repo: git@github.com:ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: c++
  link: ros_packages/mrs_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_testing
  type: git
  repo: git@github.com:ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_trackers
  type: git
  repo: git@github.com:ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_trackers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_manager
  type: git
  repo: git@github.com:ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_manager
  scripts:
  - git submodule update --init --recursive
