location: .gitman
sources:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: 19c4fc6006d88636a5b8b5f2e608bfcdf80e6620
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: https://github.com/ctu-mrs/mavros
  sparse_paths:
  -
  rev: added_dialect_file
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_bumper
  type: git
  repo: https://github.com/ctu-mrs/mrs_bumper.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_bumper
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: https://github.com/ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: https://github.com/ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: https://github.com/ctu-mrs/mrs_optic_flow.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_rviz_plugins
  type: git
  repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_rviz_plugins
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_controllers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_general
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_managers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_managers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_odometry
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_status
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_testing
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trackers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: master
  link: ros_packages/mrs_uav_trackers
  scripts:
  - git submodule update --init --recursive
- name: tmux
  type: git
  repo: https://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 3.0a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: https://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: v2.0.0
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
sources_locked:
- name: mavlink-gbp-release
  type: git
  repo: https://github.com/mavlink/mavlink-gbp-release
  sparse_paths:
  -
  rev: 19c4fc6006d88636a5b8b5f2e608bfcdf80e6620
  link: lib/mavlink-gbp-release
  scripts:
  - git submodule update --init --recursive
- name: mavros
  type: git
  repo: https://github.com/ctu-mrs/mavros
  sparse_paths:
  -
  rev: 8deab345e2560245c021b772cf675a9be54cee04
  link: ros_packages/mavros
  scripts:
  - git submodule update --init --recursive
- name: mrs_bumper
  type: git
  repo: https://github.com/ctu-mrs/mrs_bumper.git
  sparse_paths:
  -
  rev: ecb3698321ba80c74888aef875f2927718fbfa18
  link: ros_packages/mrs_bumper
  scripts:
  - git submodule update --init --recursive
- name: mrs_lib
  type: git
  repo: https://github.com/ctu-mrs/mrs_lib.git
  sparse_paths:
  -
  rev: 51583c5fed48604f24970355b624cccea889e346
  link: ros_packages/mrs_lib
  scripts:
  - git submodule update --init --recursive
- name: mrs_mavros_interface
  type: git
  repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
  sparse_paths:
  -
  rev: 2845d6c7e44ff9be594effdd48192e7ac4bb457f
  link: ros_packages/mrs_mavros_interface
  scripts:
  - git submodule update --init --recursive
- name: mrs_msgs
  type: git
  repo: https://github.com/ctu-mrs/mrs_msgs.git
  sparse_paths:
  -
  rev: 13f2d9fda2959e36c9ad9918a1a3b642da90f100
  link: ros_packages/mrs_msgs
  scripts:
  - git submodule update --init --recursive
- name: mrs_optic_flow
  type: git
  repo: https://github.com/ctu-mrs/mrs_optic_flow.git
  sparse_paths:
  -
  rev: 65babd83c7b21baf5114f467f19e0538d5e14577
  link: ros_packages/mrs_optic_flow
  scripts:
  - git submodule update --init --recursive
- name: mrs_rviz_plugins
  type: git
  repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
  sparse_paths:
  -
  rev: 154bd1b01caf08d62b2b45403eaf13b9a63504c6
  link: ros_packages/mrs_rviz_plugins
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_controllers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
  sparse_paths:
  -
  rev: 70ba9dba38adfac7df5f3bbf85a0bcd4119214b1
  link: ros_packages/mrs_uav_controllers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_general
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_general.git
  sparse_paths:
  -
  rev: 3c0178d796fe9652e2a864cf5fe604baea9a571f
  link: ros_packages/mrs_uav_general
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_managers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_managers.git
  sparse_paths:
  -
  rev: fd32e6e1a7e480e7aa321aca1dbcba506614e8c7
  link: ros_packages/mrs_uav_managers
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_odometry
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
  sparse_paths:
  -
  rev: 85b6db6f9261a8d546bdd89eedb1d19caacd6025
  link: ros_packages/mrs_uav_odometry
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_status
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_status.git
  sparse_paths:
  -
  rev: edd160f3a51c134163e44e8a3ec8945dee8d68a7
  link: ros_packages/mrs_uav_status
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_testing
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_testing.git
  sparse_paths:
  -
  rev: 73652b0e991a139284e41276560e9973c0463ffe
  link: ros_packages/mrs_uav_testing
  scripts:
  - git submodule update --init --recursive
- name: mrs_uav_trackers
  type: git
  repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
  sparse_paths:
  -
  rev: 290d413306b40cd5d85445840ef35388298d6e0a
  link: ros_packages/mrs_uav_trackers
  scripts:
  - git submodule update --init --recursive
- name: tmux
  type: git
  repo: https://github.com/tmux/tmux.git
  sparse_paths:
  -
  rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
  link: utils/tmux
  scripts:
  - git submodule update --init --recursive
- name: tmuxinator
  type: git
  repo: https://github.com/tmuxinator/tmuxinator.git
  sparse_paths:
  -
  rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
  link: utils/tmuxinator
  scripts:
  - git submodule update --init --recursive
groups: []
