location: .gitman
sources:
  - name: mavlink-gbp-release
    type: git
    repo: https://github.com/mavlink/mavlink-gbp-release
    sparse_paths:
      -
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mavros
    type: git
    repo: https://github.com/ctu-mrs/mavros
    sparse_paths:
      -
    rev: added_dialect_file
    link:
    scripts:
      - git submodule update --init --recursive
  - name: tf2
    type: git
    repo: https://github.com/ctu-mrs/tf2
    sparse_paths:
      -
    rev: warning_fix
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_bumper
    type: git
    repo: https://github.com/ctu-mrs/mrs_bumper.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_lib
    type: git
    repo: https://github.com/ctu-mrs/mrs_lib.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_mavros_interface
    type: git
    repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_msgs
    type: git
    repo: https://github.com/ctu-mrs/mrs_msgs.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_rviz_plugins
    type: git
    repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_controllers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_general
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_general.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_managers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_odometry
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_status
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_status.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_testing
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_trackers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_trajectory_generation
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: nlopt_ros
    type: git
    repo: https://github.com/ctu-mrs/nlopt_ros
    sparse_paths:
      -
    rev: master
    link:
    scripts:
      - git submodule update --init --recursive
  - name: nodelet_core
    type: git
    repo: https://github.com/ctu-mrs/nodelet_core
    sparse_paths:
      -
    rev: callback_fix
    link:
    scripts:
      - git submodule update --init --recursive
  - name: tmux
    type: git
    repo: https://github.com/tmux/tmux.git
    sparse_paths:
      -
    rev: 3.0a
    link:
    scripts:
      - git submodule update --init --recursive
  - name: tmuxinator
    type: git
    repo: https://github.com/tmuxinator/tmuxinator.git
    sparse_paths:
      -
    rev: v2.0.0
    link:
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - name: mavlink-gbp-release
    type: git
    repo: https://github.com/mavlink/mavlink-gbp-release
    sparse_paths:
      -
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mavros
    type: git
    repo: https://github.com/ctu-mrs/mavros
    sparse_paths:
      -
    rev: 8deab345e2560245c021b772cf675a9be54cee04
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_bumper
    type: git
    repo: https://github.com/ctu-mrs/mrs_bumper.git
    sparse_paths:
      -
    rev: e13ccd5ef89ec3500b6de098bd3b192bda42ec5a
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_lib
    type: git
    repo: https://github.com/ctu-mrs/mrs_lib.git
    sparse_paths:
      -
    rev: e586b9b0a79dc37c4e4fde20fe2a5af5154b4dbe
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_mavros_interface
    type: git
    repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    sparse_paths:
      -
    rev: dc4e97d4ac632b8c7fb1502bccb5be08d5938fb6
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_msgs
    type: git
    repo: https://github.com/ctu-mrs/mrs_msgs.git
    sparse_paths:
      -
    rev: a842b4a2b7e6d16d603d84d8baf3ce58efa26e23
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_rviz_plugins
    type: git
    repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    sparse_paths:
      -
    rev: da4026051af7b54575f682d64da1b3d10cf7fd0a
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_controllers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    sparse_paths:
      -
    rev: a6f0148fcdd41bd58f4dc0409fa11d358cf9a405
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_general
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_general.git
    sparse_paths:
      -
    rev: 196b3e2856c460cb7a14bc179a389f03ffdaf621
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_managers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    sparse_paths:
      -
    rev: 8d55923fd2f971b6b4f5da7340fbb7930268acef
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_odometry
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    sparse_paths:
      -
    rev: 88e75048901a6d2f0c90854c647d8e70691a961b
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_status
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_status.git
    sparse_paths:
      -
    rev: cbdbad90aa7e17cd374ce2cdc765fd0380617f6b
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_testing
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    sparse_paths:
      -
    rev: ff301d7f02908f3f50d0c7d760c616881a47597a
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_trackers
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    sparse_paths:
      -
    rev: 0638532226a953743d7ecf8b3329e71f72538b75
    link:
    scripts:
      - git submodule update --init --recursive
  - name: mrs_uav_trajectory_generation
    type: git
    repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    sparse_paths:
      -
    rev: abcba1fa22e7be5e0f0ea03ce4e1131ba20d4631
    link:
    scripts:
      - git submodule update --init --recursive
  - name: nlopt_ros
    type: git
    repo: https://github.com/ctu-mrs/nlopt_ros
    sparse_paths:
      -
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    link:
    scripts:
      - git submodule update --init --recursive
  - name: nodelet_core
    type: git
    repo: https://github.com/ctu-mrs/nodelet_core
    sparse_paths:
      -
    rev: b4344e75e9afa93010ffc20c3918ecfbab1848e4
    link:
    scripts:
      - git submodule update --init --recursive
  - name: tmux
    type: git
    repo: https://github.com/tmux/tmux.git
    sparse_paths:
      -
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    link:
    scripts:
      - git submodule update --init --recursive
  - name: tmuxinator
    type: git
    repo: https://github.com/tmuxinator/tmuxinator.git
    sparse_paths:
      -
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    link:
    scripts:
      - git submodule update --init --recursive
  - name: tf2
    type: git
    repo: https://github.com/ctu-mrs/tf2
    sparse_paths:
      -
    rev: 5863aee68ffcf385e2b70a203de47beb6a66b7f6
    link:
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
