location: .gitman
sources:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: lib/mavlink-gbp-release
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: added_dialect_file
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/tf2
    name: tf2
    rev: warning_fix
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/tf2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_mavros_interface
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_general
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_odometry
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: master
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/nlopt_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 3.0a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmux
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: v2.0.0
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmuxinator
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: lib/mavlink-gbp-release
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: 68cf7cef11d4636c59712b8afe2f3b9f74ad7865
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: 404e579919cdbf79b2ad469bd1f91a1aaa521f2a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: ebfe2e693b52527d550f094da5bda5b44b3a6879
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: 117de9f5ddb5adc638bdbcb215dd05893fb4839a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_mavros_interface
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: b2594299a5ddf3bd6f00bca8170779f5fde58c36
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: ae3e33345f82a0daf65889d2a1e8d74fdddc679d
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: 599ffa5865dfdc11e86da6e17e07c91add0252e5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: 56080142bd5a7076a96839c3663194847745d7ef
    type: git
    params:
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: 6810542ee58464adb40afe0c034fc84b07acb769
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: acf6e1fe5c89edefa3adc1b32ba551b633829a27
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_odometry
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: 7092996cd9713038eff8cf168427b9eeff4dcb26
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: bebb4b0e722846356b64055e37f52872ff040f50
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: bed1ba2607177ebffc7f47045a0171a3f3dcf1e5
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: 2b3f2edd41cd8b57b7491a5a1030b68b082986cc
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/nlopt_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmux
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmuxinator
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/tf2
    name: tf2
    rev: 89f90c21fc13868ee02e853663a226130471ea8c
    type: git
    params:
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/tf2
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
