location: .gitman
sources:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    link: lib/mavlink-gbp-release
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: added_dialect_file
    type: git
    sparse_paths:
      -
    link: ros_packages/mavros
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_bumper
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_lib
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_mavros_interface
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_msgs
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_rviz_plugins
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_controllers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_general
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_managers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_odometry
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_status
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_testing
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_trackers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_trajectory_generation
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: master
    type: git
    sparse_paths:
      -
    link: ros_packages/thirdparty/nlopt_ros
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: callback_fix
    type: git
    sparse_paths:
      -
    link: ros_packages/thirdparty/nodelet_core
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 3.0a
    type: git
    sparse_paths:
      -
    link: utils/tmux
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: v2.0.0
    type: git
    sparse_paths:
      -
    link: utils/tmuxinator
    links:
      -
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    link: lib/mavlink-gbp-release
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: 8deab345e2560245c021b772cf675a9be54cee04
    type: git
    sparse_paths:
      -
    link: ros_packages/mavros
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: 6aaf450b5170f11c35536c48404340a287446821
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_bumper
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: 92f811efee7fe2ea7f44decbf382b1426acd39ba
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_lib
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: 83b540ee0637ea739e59f4313bfd16d462fbb18c
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_mavros_interface
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: bd2b456abd7d3c9be33e4eb0ceb31bf60dae3955
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_msgs
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: bf7ea90ce58b98526cd359d8f70659451dbbcff6
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_rviz_plugins
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: 07dfd70238102a9ce75a7820d39e125499056649
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_controllers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: 988925f7b3b7c1f5ac9e5603ab7e88c34061d0ea
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_general
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: b9d31c91d67eca454b0cc72345c3d5d22b181641
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_managers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: 1ad407bbf5b2febf25ebc4cb90e3c7cdc4155c53
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_odometry
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: 6f944b87a5b47935a4af73a66cef4969f1043d01
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_status
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: d22fd558d5d51e965cafd3229943a263557e180d
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_testing
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: e68cd4f6cdb45612cd6c183104fdde2148810c68
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_trackers
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: 898a4c61d59e4947672b74b411ffe958d29235c6
    type: git
    sparse_paths:
      -
    link: ros_packages/mrs_uav_trajectory_generation
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    type: git
    sparse_paths:
      -
    link: ros_packages/thirdparty/nlopt_ros
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: b4344e75e9afa93010ffc20c3918ecfbab1848e4
    type: git
    sparse_paths:
      -
    link: ros_packages/thirdparty/nodelet_core
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    type: git
    sparse_paths:
      -
    link: utils/tmux
    links:
      -
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    type: git
    sparse_paths:
      -
    link: utils/tmuxinator
    links:
      -
    scripts:
      - git submodule update --init --recursive
groups:
  -
default_group: ''
