location: .gitman
sources:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: lib/mavlink-gbp-release
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: added_dialect_file
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/tf2
    name: tf2
    rev: warning_fix
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/tf2
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_mavros_interface
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_general
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_odometry
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: master
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/nlopt_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: callback_fix
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/nodelet_core
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 3.0a
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmux
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: v2.0.0
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmuxinator
    scripts:
      - git submodule update --init --recursive
sources_locked:
  - repo: https://github.com/mavlink/mavlink-gbp-release
    name: mavlink-gbp-release
    rev: 0dc40a07d97e665c563600081840c45b60bae1cf
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: lib/mavlink-gbp-release
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mavros
    name: mavros
    rev: 8deab345e2560245c021b772cf675a9be54cee04
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mavros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_bumper.git
    name: mrs_bumper
    rev: e13ccd5ef89ec3500b6de098bd3b192bda42ec5a
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_bumper
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_lib.git
    name: mrs_lib
    rev: 14240919db5123814650951535a01b3a4ec47bb6
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_lib
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_mavros_interface.git
    name: mrs_mavros_interface
    rev: dc4e97d4ac632b8c7fb1502bccb5be08d5938fb6
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_mavros_interface
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_msgs.git
    name: mrs_msgs
    rev: a842b4a2b7e6d16d603d84d8baf3ce58efa26e23
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_msgs
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_rviz_plugins.git
    name: mrs_rviz_plugins
    rev: da4026051af7b54575f682d64da1b3d10cf7fd0a
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_rviz_plugins
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_controllers.git
    name: mrs_uav_controllers
    rev: aaad2cc178cd7d1a45e3f9a93af7277b94d02d5a
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_controllers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_general.git
    name: mrs_uav_general
    rev: f1e0e4bc33780e9298ca6bdd0079f8f61f98a978
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_general
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_managers.git
    name: mrs_uav_managers
    rev: 1f629cebd97ca753f6207858d45025472177a17b
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_managers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_odometry.git
    name: mrs_uav_odometry
    rev: 8cb02914766cb2e7a11c33ded812d9b32794aa89
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_odometry
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_status.git
    name: mrs_uav_status
    rev: cbdbad90aa7e17cd374ce2cdc765fd0380617f6b
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_status
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_testing.git
    name: mrs_uav_testing
    rev: ff301d7f02908f3f50d0c7d760c616881a47597a
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_testing
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trackers.git
    name: mrs_uav_trackers
    rev: 59f2870d94d7260c662e7b6ff0ee42f13a25b5d9
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trackers
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/mrs_uav_trajectory_generation
    name: mrs_uav_trajectory_generation
    rev: 70257d4e7d292f87b29666f0189d0eca3b3b5f53
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/mrs_uav_trajectory_generation
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nlopt_ros
    name: nlopt_ros
    rev: 5e351e81e8ee0c39d3096f38a0aa990304298631
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/nlopt_ros
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/nodelet_core
    name: nodelet_core
    rev: b4344e75e9afa93010ffc20c3918ecfbab1848e4
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: ros_packages/thirdparty/nodelet_core
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmux/tmux.git
    name: tmux
    rev: 25ae02869544b84b639b25b0aa69baa6ea2d3a6a
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmux
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/tmuxinator/tmuxinator.git
    name: tmuxinator
    rev: 7208ab2ed7c8cfbcbe92c4b0db2bc01550d40fd4
    type: git
    sparse_paths:
      -
    links:
      - source: ''
        target: utils/tmuxinator
    scripts:
      - git submodule update --init --recursive
  - repo: https://github.com/ctu-mrs/tf2
    name: tf2
    rev: 5863aee68ffcf385e2b70a203de47beb6a66b7f6
    type: git
    sparse_paths:
      -
    links:
      -
    scripts:
      - git submodule update --init --recursive
default_group: ''
groups:
  -
